# Generated by Django 5.0.6 on 2024-06-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app9', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meeting',
        ),
    ]
