# Generated by Django 5.0.6 on 2024-06-23 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app9', '0002_delete_meeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrolment',
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
