# Generated by Django 5.0.6 on 2024-06-23 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app9', '0003_remove_student_enrolment_delete_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='plangauges',
            new_name='planguages',
        ),
    ]
